### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by gonvaled** [Yupeek/django-rest-models#24]
Hi @ornoone, thanks for this project.

I have started using it, and would like to know if the project is being actively maintained.

I have noticed that it is not compatible with Django 1.11, and Django 1.10 is EOL. Do you have an upgrade roadmap?

**Comment by ornoone** [comment]
@gonvaled before deploying to pypi, do you want to test in real project if you have the requirements ? 
we can't upgrande to django 1.11 our main project now, so I can't check with real life project.
