### ISSUE TITLE
Django 2.0 support

### ISSUE THREAD

**Issue by FeroxTL** [Yupeek/django-rest-models#29]
I'm trying to run this project under Django 2.0.5 and there is a question -- is it supported?

For now I have running both targeted api and client with django 2.0. At first look targeted API works fine. But client api doesn't. In fact I have a problem -- function django.db.models.sql.compiler.SQLCompiler#execute_sql has different interface now:

```
def execute_sql(self, result_type=MULTI, chunked_fetch=False, chunk_size=GET_ITERATOR_CHUNK_SIZE):
```

but rest_models.backend.compiler.SQLCompiler#execute_sql has another:

```
def execute_sql(self, result_type=MULTI, chunked_fetch=False):
```

so when I try to execute any query for example MyModel.objects.get() it raises exception:

```
execute_sql() got an unexpected keyword argument 'chunk_size'

.../site-packages/django/db/models/query.py in __iter__
        def __iter__(self):
            <skipped>
            results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
```

I was able to fix this with adding **kwargs to SQLCompiler#execute_sql but i'm not sure if it works correct

```
def execute_sql(self, result_type=MULTI, chunked_fetch=False, **kwargs):
```

**Comment by ornoone** [comment]
hello @FeroxTL, we currently don't support django 2.0 for one main reason : the tools used in the api end (dynamic-rest) is not compatible with 2.0. It require to change the way the tests are ran to use 2 version of django for client and server durring unit tests. 

in fact, your fix is correct since we indicate to django that we don't support chunked_fetch and so, the chunk_size will never be meaningfull in this call.

**Comment by FeroxTL** [comment]
@ornoone thank you for the reply

Am I right that you are waiting for django 2.0 support in underlying libraries (dynamic-rest) or this is architecture problem of django-rest-models?

It seems that dynamic-rest recently merged support of 2.0 https://github.com/AltSchool/dynamic-rest/issues/217 but didn't update readme

**Comment by ornoone** [comment]
i just released a rc to check if this fix your problem. 
https://pypi.org/project/django-rest-models/1.6.1rc3/

**Comment by RabidCicada** [comment]
I'm using django-rest-models right now with 2.0 and it all works.  Bit of a learning curve with the dynamic-rest etc...but working out.

**Comment by seljin** [comment]
Hi there !

Sorry for the enormous response time, it now fully supports django 2.0, 2.1 and 2.2

Thanks y'all for using django-rest-models
