### ISSUE TITLE
django-restframework-jsonapi support?

### ISSUE THREAD

**Issue by n2ygk** [Yupeek/django-rest-models#35]
On a cursory look, it seems [django-restframework-json-api](https://github.com/django-json-api/django-rest-framework-json-api) (DJA), an implementation of the  [JSON:API](http://jsonapi.org) request/response format, is similar to DREST. Would it be reasonable to try extending this package to use DJA as an alternative backend to DREST?

See also https://github.com/django-json-api/django-rest-framework-json-api/issues/472

**Comment by ornoone** [comment]
I don't think DJA can be an alternative to DREST, since the main usage of DREST is the `DynamicModelViewSet` and the `DynamicRouter`. what i saw in DJA is it's a better serializer to be standard compliant for JSON:API.
