### ISSUE TITLE
Make contentType optional in sql insert and update.  

### ISSUE THREAD

**Issue by RabidCicada** [Yupeek/django-rest-models#57]
Make contentType optional in SQLInsertCompiler and SQLUpdateCompiler.  This allows a regular django.core.files.base.File() object to be fed to django-rest-models.  The django-rest-models setup currently just expects the content_type to exist and blindly references it.  My particular use case is a django-admin command on the django-rest-models consumer app to allow import of files into the system.  The general usecase is to let anyone simply use a django File() object to feed a django-rest-model.

```
def _import_stuff(self, tmpdir):
      gen_exp = (d for d in tmpdir.iterdir() if d.is_dir())
      for d in gen_exp:
          with open(str(d / 'data.json'), 'r') as f:
              deserializer = serializers.deserialize("json", f.read())
              for deserialized_stuff in deserializer:
                  newstuff = deserialized_stuff.object

                  for field in newstuff._meta.fields: # pylint: disable=protected-access
                      if isinstance(field, models.FileField):
                          field = getattr(newstuff, field.attname)
                          if field:
                              thefile = File(open(str(d / str(field)), 'rb'))
                              field.save(str(field), thefile, save=False)

                  #Save entire model
                  newstuff.save(force_insert=True)

```

**Comment by RabidCicada** [comment]
I've tested defaulting to None and it works.  I've looked around and we could also default to 'application/octet-stream' though I have not tested that.

**Comment by seljin** [comment]
Thank you for your time :+1: 

Don't hesitate to request us if you want to add the DEFAULT_CONTENT_TYPE setting

**Comment by seljin** [comment]
Don't hesitate to request us if you want to add the

**Comment by seljin** [comment]
Thank you for your time :+1: 

Don't hesitate to request us if you want to add the DEFAULT_CONTENT_TYPE setting
