### ISSUE TITLE
Django 4.2 support

### ISSUE THREAD

**Issue by nik0mon** [Yupeek/django-rest-models#84]
Hi guys. We are trying to upgrade our application to use Django 4.2 but it seems as though django-rest-models only support up to Django 3.2. I noticed that there is a branch for 4.2 support and @seljin was working on it. I was wondering if there is a timeline as to when the support for 4.2 would be available? Thanks for your hardwork and for this awesome package.

**Comment by seljin** [comment]
Hello,

Release 3.0.0 is compatible with django up to 5.1 

Enjoy :)
